### ISSUE TITLE
Update to Vega-Lite-API 

### ISSUE THREAD

**Issue by arky** [okfn/ckanext-vegaview#5]
Any chances of updating this extension for newer [Vega-Lite-API](https://vega.github.io/vega-lite-api/) @vitorbaptista ?

**Comment by vitorbaptista** [comment]
Hey @arky, what advantages vega-lite would bring and how involved do you think this migration would be? I'd be happy to review a PR, but I'm unable to drive this change at the moment.

**Comment by arky** [comment]
Vega-Lite-API makes it easier to write charts for JavaScript developers.  The reason I never used JSON based charts is that it really difficult to debug esp. in a simple web form.

**Comment by vitorbaptista** [comment]
From what I understood, Vega-Lite API allows you to use a JS code to generate Vega's JSON? If so, in theory, someone could use the Vega-Lite API in some other place, generate the Vega JSON, and use ckanext-vegaview as is?

**Comment by arky** [comment]
Let me take that approach to generate JSON in a observable notebook and paste the output.
